import numpy as np
arr = np.array([[ 4, 34, 5, 6, 3, 5], [3, 78, 34, 64, 14, 75]])
print(arr[0:5])
print(arr[1:1])
print(arr[1:6])
print(arr[-4:-1])
print("--------------------")
print(arr[1:6:2])
print("----------------")
print(arr[::2])
print("----------------")
print(arr[:2,2])
print("----------------")
print(arr[1, 1:4])
print("----------------")
print(arr[:4, 1:4])
print("----------------")
print(arr[1, 1:3])
print("----------------")
print(arr.dtype)